import {RouteObject} from "react-router-dom";
const routes: RouteObject[] = [];
import Analytics from "./src/pages/analytics";
routes.push({ path: "/analytics", element: <Analytics /> });
import Audit from "./src/pages/audit";
routes.push({ path: "/audit", element: <Audit /> });
import Commands from "./src/pages/commands";
routes.push({ path: "/commands", element: <Commands /> });
import Console from "./src/pages/console";
routes.push({ path: "/console", element: <Console /> });
import Groups from "./src/pages/groups";
routes.push({ path: "/groups", element: <Groups /> });
import Index from "./src/pages/index";
routes.push({ path: "/", element: <Index /> });
import Login from "./src/pages/login";
routes.push({ path: "/login", element: <Login /> });
import Players from "./src/pages/players";
routes.push({ path: "/players", element: <Players /> });
import Rbac from "./src/pages/rbac";
routes.push({ path: "/rbac", element: <Rbac /> });
import Reports from "./src/pages/reports";
routes.push({ path: "/reports", element: <Reports /> });
import Status from "./src/pages/status";
routes.push({ path: "/status", element: <Status /> });
export default routes;
